version: '3'
services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:90'
    depends_on:
      - db

  db:
    image: mysql:5.7
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data:
    driver: local